### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
Changing paths to headers needs to be tested in a _clean_ bootstrap. Otherwise, leftover headers are usually there to make sure things "look" fine.

**Comment by marvin2k** [comment]
One trick (I'm sure you know about it) to improve the situation after header renames is to insert an `#error` or `#warning` statement into the to-be-replaced header, forcing the compiler to stop in case the header is still in use.

**Comment by 2maz** [comment]
completely agree with @doudou -- base-logging should not have been merged until tested properly

**Comment by 2maz** [comment]
apart from that: the project name 'base-logging' is not really compliant -- either it is then installed into base/base-logging or it should be named 'logging'

**Comment by doudou** [comment]
> apart from that: the project name 'base-logging' is not really compliant -- either it is then installed into base/base-logging or it should be named 'logging'

Agreed. I left it out, don't have to time for this kind of obvious discussions that should have been done before the fact.

**Pull request merged**
